{
 "title": "ESP8266 BME",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(bme_up, exported_instance)"
    }
   },
   { "name": "room", "query": { "query": "label_values(bme_up, room)" } }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "bme_temperature{exported_instance=~\"$instance\", room=~\"$room\"}",
     "legendFormat": "{{ exported_instance }} - {{ room }}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "bme_humidity{exported_instance=~\"$instance\", room=~\"$room\"}",
     "legendFormat": "{{ exported_instance }} - {{ room }}"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "targets": [
    {
     "expr": "bme_pressure{exported_instance=~\"$instance\", room=~\"$room\"}",
     "legendFormat": "{{ exported_instance }} - {{ room }}"
    }
   ]
  },
  {
   "title": "Heat Index",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "bme_heat_index{exported_instance=~\"$instance\", room=~\"$room\"}",
     "legendFormat": "{{ exported_instance }} - {{ room }}"
    }
   ]
  },
  {
   "title": "Dew Point",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "bme_dew_point{exported_instance=~\"$instance\", room=~\"$room\"}",
     "legendFormat": "{{ exported_instance }} - {{ room }}"
    }
   ]
  }
 ]
}